from fastapi import APIRouter

from app.routes import (
    admin,
    admin_betting_picks,
    admin_bookmakers,
    admin_competition_ingest,
    admin_competitions,
    admin_jobs,
    admin_referees,
    admin_debug_player_db,
    admin_data_health,
    admin_debug_api_football_catalog,
    admin_debug_player_stats,
    admin_debug_offensive_variables,
    admin_debug_expected_goals,
    admin_debug_team_shot_stats,
    admin_features_player_season_profiles,
    admin_ingest,
    admin_pipeline,
    admin_refresh,
    admin_sportapi,
    betting_picks,
    backtest,
    backtest_debug,
    backtest_round_analysis,
    backtest_runs,
    competition_scoped,
    competitions,
    data_catalog,
    debug_sot,
    dashboard,
    features,
    health,
    h2h,
    ingestion,
    match_analysis,
    match_context,
    model,
    player_sot_profiles,
    predictions,
    standings,
)

api_router = APIRouter(prefix="/api")
api_router.include_router(health.router, tags=["health"])
api_router.include_router(admin.router, tags=["admin"])
api_router.include_router(admin_debug_player_db.router)
api_router.include_router(admin_debug_player_stats.router)
api_router.include_router(admin_debug_api_football_catalog.router)
api_router.include_router(admin_debug_offensive_variables.router)
api_router.include_router(admin_debug_expected_goals.router)
api_router.include_router(admin_debug_team_shot_stats.router)
api_router.include_router(admin_ingest.router)
api_router.include_router(admin_features_player_season_profiles.router)
api_router.include_router(admin_pipeline.router)
api_router.include_router(admin_refresh.router)
api_router.include_router(admin_data_health.router)
api_router.include_router(admin_sportapi.router)
api_router.include_router(admin_jobs.router)
api_router.include_router(admin_referees.router)
api_router.include_router(admin_betting_picks.router)
api_router.include_router(admin_bookmakers.router)
api_router.include_router(admin_competitions.router)
api_router.include_router(admin_competition_ingest.router)
api_router.include_router(competitions.router)
api_router.include_router(competition_scoped.router)
api_router.include_router(betting_picks.router)
api_router.include_router(ingestion.router)
api_router.include_router(dashboard.router)
api_router.include_router(features.router)
api_router.include_router(predictions.router)
api_router.include_router(backtest.router)
api_router.include_router(backtest_runs.router)
api_router.include_router(backtest_debug.router)
api_router.include_router(backtest_round_analysis.router)
api_router.include_router(player_sot_profiles.router)
api_router.include_router(h2h.router)
api_router.include_router(standings.router)
api_router.include_router(match_context.router)
api_router.include_router(model.router)
api_router.include_router(data_catalog.router)
api_router.include_router(match_analysis.router)
api_router.include_router(debug_sot.router)
