from fastapi import APIRouter

from app.core.constants import BASELINE_SOT_MODEL_VERSION, BASELINE_SOT_MODEL_VERSION_V02
from app.schemas.model import MatchAnalysisFrameworkResponse, ModelLegendResponse
from app.services.sot_prediction_service import WEIGHTS_BASELINE_V0_1

router = APIRouter(prefix="/model", tags=["model"])


@router.get("/legend", response_model=ModelLegendResponse)
def get_model_legend() -> ModelLegendResponse:
    w = WEIGHTS_BASELINE_V0_1
    return ModelLegendResponse(
        model_version="baseline_v0_2_player_adjusted",
        title="Legenda modello tiri in porta",
        description=(
            "Questa legenda mostra quali fattori vengono usati per stimare "
            "i tiri in porta attesi di una squadra."
        ),
        expected_sot_formula=(
            "baseline_expected_sot (v0.1) = 0.30 × media stagionale squadra + 0.25 × media concessa avversario "
            "+ 0.15 × media casa/fuori squadra + 0.10 × media concessa casa/fuori avversario "
            "+ 0.10 × ultime 5 squadra + 0.10 × ultime 5 concesse avversario\n"
            "adjusted_expected_sot (v0.2 player adjusted) = baseline_expected_sot + player_adjustment"
        ),
        sections=[
            {
                "id": "baseline_formula",
                "title": "Baseline v0.1 (modello squadra puro)",
                "status": "applicata",
                "description": "Questa sezione è la formula storica della baseline v0.1 e resta invariata.",
                "variables": [
                    {
                        "technical_key": "season_avg_sot_for",
                        "name": "Media stagionale tiri in porta fatti",
                        "description": (
                            "Misura quanti tiri in porta produce mediamente la squadra "
                            "nella stagione prima della partita."
                        ),
                        "weight": w["season_avg_sot_for"],
                        "weight_label": "30%",
                        "status": "applicata",
                        "impact": "Aumenta expected_sot quando la produzione media è alta.",
                        "interpretation": "Più è alta, più aumenta la previsione.",
                    },
                    {
                        "technical_key": "opponent_season_avg_sot_conceded",
                        "name": "Tiri in porta concessi dall’avversario",
                        "description": "Misura quanti tiri in porta concede mediamente l’avversario.",
                        "weight": w["opponent_season_avg_sot_conceded"],
                        "weight_label": "25%",
                        "status": "applicata",
                        "impact": "Aumenta expected_sot se l’avversario concede tanto.",
                        "interpretation": (
                            "Se l’avversario concede tanto, la previsione della squadra aumenta."
                        ),
                    },
                    {
                        "technical_key": "home_away_avg_sot_for",
                        "name": "Media casa/fuori della squadra",
                        "description": (
                            "Misura il rendimento della squadra nello stesso contesto "
                            "della partita: casa o trasferta."
                        ),
                        "weight": w["home_away_avg_sot_for"],
                        "weight_label": "15%",
                        "status": "applicata",
                        "impact": "Corregge expected_sot sul contesto casa/trasferta.",
                        "interpretation": "Serve a distinguere squadre più forti in casa o fuori.",
                    },
                    {
                        "technical_key": "opponent_home_away_avg_sot_conceded",
                        "name": "Tiri concessi dall’avversario casa/fuori",
                        "description": (
                            "Misura quanto concede l’avversario quando gioca nello stesso "
                            "contesto della partita."
                        ),
                        "weight": w["opponent_home_away_avg_sot_conceded"],
                        "weight_label": "10%",
                        "status": "applicata",
                        "impact": "Regola expected_sot sul comportamento contestuale dell’avversario.",
                        "interpretation": "Aiuta a capire se l’avversario concede di più in casa o fuori.",
                    },
                    {
                        "technical_key": "last5_avg_sot_for",
                        "name": "Forma recente della squadra",
                        "description": (
                            "Media dei tiri in porta prodotti dalla squadra "
                            "nelle ultime 5 partite disponibili."
                        ),
                        "weight": w["last5_avg_sot_for"],
                        "weight_label": "10%",
                        "status": "applicata",
                        "impact": "Adatta expected_sot al trend più recente.",
                        "interpretation": "Serve a intercettare trend recenti.",
                    },
                    {
                        "technical_key": "opponent_last5_avg_sot_conceded",
                        "name": "Forma recente difensiva dell’avversario",
                        "description": (
                            "Media dei tiri in porta concessi dall’avversario nelle ultime 5 partite."
                        ),
                        "weight": w["opponent_last5_avg_sot_conceded"],
                        "weight_label": "10%",
                        "status": "applicata",
                        "impact": "Aumenta expected_sot quando l’avversario concede tanto di recente.",
                        "interpretation": (
                            "Se l’avversario concede tanto di recente, la previsione aumenta."
                        ),
                    },
                ],
            },
            {
                "id": "baseline_v02_context_player",
                "title": "Modello live v0.2 Player Adjusted",
                "status": "applicata",
                "description": (
                    "Il modello live parte dalla baseline v0.1 e applica una correzione prudente "
                    "basata sull’impatto giocatori."
                ),
                "variables": [
                    {
                        "technical_key": "model_version_v01",
                        "name": "Versione baseline storica",
                        "description": "Versione di partenza del calcolo.",
                        "weight": None,
                        "weight_label": None,
                        "status": "applicata",
                        "impact": "Mantiene compatibilità con la baseline originale.",
                        "interpretation": f"Valore: {BASELINE_SOT_MODEL_VERSION}",
                    },
                    {
                        "technical_key": "model_version_v02",
                        "name": "Versione adjustment contestuali",
                        "description": "Nuova versione con correzioni spiegabili.",
                        "weight": None,
                        "weight_label": None,
                        "status": "applicata",
                        "impact": "Aggiunge correzioni prudenti senza sostituire v0.1.",
                        "interpretation": f"Valore: {BASELINE_SOT_MODEL_VERSION_V02}",
                    },
                    {
                        "technical_key": "expected_sot_v02_formula",
                        "name": "Formula v0.2",
                        "description": (
                            "adjusted_expected_sot = baseline_expected_sot + player_adjustment"
                        ),
                        "weight": None,
                        "weight_label": None,
                        "status": "applicata",
                        "impact": "Calcola il valore aggiustato finale per team.",
                        "interpretation": "Somma baseline v0.1 + correzione giocatori (prudente).",
                    },
                    {
                        "technical_key": "adjustment_caps",
                        "name": "Cap adjustment",
                        "description": "Cap player_adjustment: ±0.35 (gli altri layer non sono ancora applicati).",
                        "weight": None,
                        "weight_label": None,
                        "status": "applicata",
                        "impact": "Evita correzioni eccessive e migliora robustezza.",
                        "interpretation": "Le correzioni restano prudenti e tracciabili.",
                    },
                ],
            },
            {
                "id": "player_impact",
                "title": "Impatto giocatori",
                "status": "applicata",
                "description": (
                    "La correzione giocatori è applicata nel modello live v0.2 Player Adjusted. "
                    "Non è applicata nella baseline storica v0.1."
                ),
                "variables": [
                    {
                        "technical_key": "shots_on_target_per90",
                        "name": "Tiri in porta per 90 minuti",
                        "description": "Misura quanti tiri in porta produce il giocatore ogni 90 minuti.",
                        "weight": 0.60,
                        "weight_label": "60%",
                        "status": "applicata",
                        "impact": "Aiuta a stimare il contributo offensivo individuale.",
                        "interpretation": "Valori più alti indicano giocatori più presenti al tiro.",
                    },
                    {
                        "technical_key": "team_sot_share_pct",
                        "name": "Quota dei tiri in porta della squadra",
                        "description": (
                            "Indica quanto il giocatore pesa sulla produzione totale "
                            "di tiri in porta della squadra."
                        ),
                        "weight": 0.25,
                        "weight_label": "25%",
                        "status": "applicata",
                        "impact": "Misura centralità del giocatore nel volume offensivo.",
                        "interpretation": (
                            "Percentuali alte suggeriscono dipendenza della squadra da quel giocatore."
                        ),
                    },
                    {
                        "technical_key": "reliability_score",
                        "name": "Affidabilità del campione",
                        "description": "Tiene conto di minuti giocati e presenze.",
                        "weight": 0.15,
                        "weight_label": "15%",
                        "status": "applicata",
                        "impact": "Riduce il peso di campioni piccoli o poco stabili.",
                        "interpretation": (
                            "Più è alto, più il profilo è statisticamente affidabile."
                        ),
                    },
                    {
                        "technical_key": "impact_score_formula",
                        "name": "Formula player impact",
                        "description": (
                            "impact_score = 0.60 × tiri in porta per 90 normalizzati + "
                            "0.25 × quota tiri squadra + 0.15 × affidabilità"
                        ),
                        "weight": None,
                        "weight_label": None,
                        "status": "applicata",
                        "impact": "Usata per stimare la correzione giocatori nel modello live v0.2.",
                        "interpretation": (
                            "Nei match futuri la correzione è prudente e tracciabile nel breakdown."
                        ),
                    },
                ],
            },
            {
                "id": "h2h",
                "title": "Scontri diretti",
                "status": "solo_debug",
                "description": (
                    "Gli scontri diretti aiutano a leggere il contesto storico tra due squadre, "
                    "ma al momento non modificano matematicamente expected_sot."
                ),
                "variables": [
                    {
                        "technical_key": "matches_total",
                        "name": "Partite H2H nel campione",
                        "description": "Numero di scontri diretti conclusi considerati nel riepilogo.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Solo lettura del contesto storico.",
                        "interpretation": "Campione più ampio rende il riepilogo più robusto.",
                    },
                    {
                        "technical_key": "home_team_wins",
                        "name": "Vittorie squadra casa negli H2H",
                        "description": "Conteggio vittorie lato casa nel campione storico.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Nessun impatto diretto sul calcolo expected_sot.",
                        "interpretation": "Aiuta a contestualizzare l'equilibrio storico.",
                    },
                    {
                        "technical_key": "away_team_wins",
                        "name": "Vittorie squadra trasferta negli H2H",
                        "description": "Conteggio vittorie lato trasferta nel campione storico.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Nessun impatto diretto sul calcolo expected_sot.",
                        "interpretation": "Aiuta a leggere eventuali trend storici sfavorevoli/favorevoli.",
                    },
                    {
                        "technical_key": "draws",
                        "name": "Pareggi negli H2H",
                        "description": "Conteggio pareggi nel campione storico.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Nessun impatto diretto sul calcolo expected_sot.",
                        "interpretation": "Indica livello di equilibrio storico tra le squadre.",
                    },
                    {
                        "technical_key": "avg_total_goals",
                        "name": "Media gol totali H2H",
                        "description": "Media gol totali nelle partite H2H concluse del campione.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Indicatore descrittivo, non usato nella formula baseline.",
                        "interpretation": "Suggerisce se gli scontri storici sono stati più o meno aperti.",
                    },
                    {
                        "technical_key": "avg_total_sot",
                        "name": "Media tiri in porta totali H2H",
                        "description": "Media tiri in porta totali H2H se il dato è disponibile nel DB.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Indicatore descrittivo, non usato nella formula baseline.",
                        "interpretation": "Utile solo come contesto aggiuntivo.",
                    },
                    {
                        "technical_key": "h2h_sample_limited",
                        "name": "Campione H2H limitato",
                        "description": "Flag che segnala un numero ridotto di match storici disponibili.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Aumenta cautela interpretativa sul riepilogo H2H.",
                        "interpretation": "Se vero, leggere i dati H2H con prudenza.",
                    },
                ],
            },
            {
                "id": "match_context",
                "title": "Contesto e motivazione partita",
                "status": "solo_debug",
                "description": (
                    "Questo layer valuta il peso reale della partita, soprattutto a fine stagione. "
                    "Al momento genera warning e note di prudenza, ma non modifica ancora expected_sot."
                ),
                "variables": [
                    {
                        "technical_key": "motivation_level",
                        "name": "Livello motivazione",
                        "description": "Stima qualitativa della motivazione della squadra.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Warning qualitativo, nessun impatto matematico.",
                        "interpretation": "Aiuta a capire quanto la classifica può influire sull'approccio gara.",
                    },
                    {
                        "technical_key": "competition_objective",
                        "name": "Obiettivo competitivo",
                        "description": (
                            "Classifica l'obiettivo principale: titolo, champions, europa, salvezza o incerto."
                        ),
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Solo contesto qualitativo.",
                        "interpretation": "Fornisce un quadro sintetico della posta in palio.",
                    },
                    {
                        "technical_key": "turnover_risk",
                        "name": "Rischio turnover",
                        "description": "Stima prudenziale del rischio di rotazioni.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Solo warning di prudenza.",
                        "interpretation": "Non implica certezze sulle formazioni.",
                    },
                    {
                        "technical_key": "late_season_risk",
                        "name": "Rischio fine stagione",
                        "description": "Flag che segnala round avanzato e maggiore variabilità del contesto.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Solo warning di affidabilità contestuale.",
                        "interpretation": "A fine stagione il modello va letto con maggiore cautela.",
                    },
                    {
                        "technical_key": "risk_flags",
                        "name": "Flag di rischio partita",
                        "description": "Elenco sintetico di segnali di rischio estratti dal contesto.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Solo warning in UI.",
                        "interpretation": "Aiuta a individuare partite da interpretare con prudenza.",
                    },
                    {
                        "technical_key": "overall_match_importance",
                        "name": "Importanza complessiva partita",
                        "description": "Valutazione complessiva dell'importanza competitiva del match.",
                        "weight": None,
                        "weight_label": None,
                        "status": "solo_debug",
                        "impact": "Informazione contestuale, non entra nella formula.",
                        "interpretation": "Sintesi finale del contesto motivazionale.",
                    },
                ],
            },
            {
                "id": "confidence",
                "title": "Affidabilità della previsione",
                "status": "applicata_alla_lettura",
                "description": (
                    "Queste metriche aiutano a leggere il risultato, ma non cambiano expected_sot."
                ),
                "variables": [
                    {
                        "technical_key": "data_quality_score",
                        "name": "Qualità dati",
                        "description": "Misura la completezza dei dati disponibili.",
                        "weight": None,
                        "weight_label": None,
                        "status": "applicata_alla_lettura",
                        "impact": "Migliora o riduce la fiducia nella lettura del risultato.",
                        "interpretation": "Può essere alta anche se la previsione non è perfetta.",
                    },
                    {
                        "technical_key": "prediction_confidence_score",
                        "name": "Affidabilità previsione",
                        "description": (
                            "Misura quanto leggere con fiducia la previsione, considerando anche il backtest."
                        ),
                        "weight": None,
                        "weight_label": None,
                        "status": "applicata_alla_lettura",
                        "impact": "Guida l'interpretazione finale del numero previsto.",
                        "interpretation": (
                            "Nel modello baseline_v0_1 è limitata in modo prudente perché il MAE è circa 1.76."
                        ),
                    },
                    {
                        "technical_key": "mae",
                        "name": "MAE",
                        "description": "Errore medio assoluto del modello.",
                        "weight": None,
                        "weight_label": None,
                        "status": "applicata_alla_lettura",
                        "impact": "Riferimento chiave per valutare l'errore medio atteso.",
                        "interpretation": (
                            "Sotto 1.50 = buono; 1.50-2.00 = accettabile; sopra 2.00 = da migliorare."
                        ),
                    },
                    {
                        "technical_key": "rmse",
                        "name": "RMSE",
                        "description": "Errore che penalizza maggiormente gli scostamenti grandi.",
                        "weight": None,
                        "weight_label": None,
                        "status": "applicata_alla_lettura",
                        "impact": "Evidenzia presenza di partite con errori più ampi.",
                        "interpretation": "Serve a capire se ci sono partite in cui il modello sbaglia molto.",
                    },
                ],
            },
            {
                "id": "not_yet_applied",
                "title": "Fattori non ancora applicati",
                "status": "non_applicata",
                "description": (
                    "Questi fattori sono monitorati o pianificati, ma non entrano "
                    "ancora nel calcolo matematico della baseline."
                ),
                "variables": [
                    {
                        "technical_key": "expected_lineups",
                        "name": "Probabili formazioni",
                        "description": "Probabili pre-partita da integrare in versioni future.",
                        "weight": None,
                        "weight_label": None,
                        "status": "non_applicata",
                        "impact": "Nessun impatto su expected_sot baseline.",
                        "interpretation": "Per ora da verificare con fonti esterne.",
                    },
                    {
                        "technical_key": "official_lineups",
                        "name": "Formazioni ufficiali",
                        "description": "Formazioni confermate poco prima del match.",
                        "weight": None,
                        "weight_label": None,
                        "status": "non_applicata",
                        "impact": "Nessun impatto su expected_sot baseline.",
                        "interpretation": "Non ancora integrate nella formula.",
                    },
                    {
                        "technical_key": "injuries_absences",
                        "name": "Infortuni/assenze/squalifiche",
                        "description": "Eventi disponibilità giocatori durante la stagione.",
                        "weight": None,
                        "weight_label": None,
                        "status": "non_applicata",
                        "impact": "Nessun impatto su expected_sot baseline.",
                        "interpretation": "Per ora solo contesto informativo.",
                    },
                    {
                        "technical_key": "bookmaker_odds_auto",
                        "name": "Quote bookmaker automatiche",
                        "description": "Import automatico quote e segnali mercato.",
                        "weight": None,
                        "weight_label": None,
                        "status": "non_applicata",
                        "impact": "Nessun impatto su expected_sot baseline.",
                        "interpretation": "La linea bookmaker resta un input manuale di lettura.",
                    },
                    {
                        "technical_key": "player_impact_in_formula",
                        "name": "Player impact nella formula finale",
                        "description": "Integrazione diretta di impact_score nel calcolo expected_sot.",
                        "weight": None,
                        "weight_label": None,
                        "status": "non_applicata",
                        "impact": "Nessun impatto su expected_sot baseline.",
                        "interpretation": "Previsto in evoluzioni future del modello.",
                    },
                    {
                        "technical_key": "h2h_in_formula",
                        "name": "H2H nella formula finale",
                        "description": "Uso quantitativo del contesto scontri diretti.",
                        "weight": None,
                        "weight_label": None,
                        "status": "non_applicata",
                        "impact": "Nessun impatto su expected_sot baseline.",
                        "interpretation": "Per ora H2H resta solo supporto di lettura.",
                    },
                    {
                        "technical_key": "motivation_context_in_formula",
                        "name": "Motivation context nella formula finale",
                        "description": "Integrazione quantitativa del layer motivazionale.",
                        "weight": None,
                        "weight_label": None,
                        "status": "non_applicata",
                        "impact": "Nessun impatto su expected_sot baseline.",
                        "interpretation": "Per ora il layer motivation produce solo warning.",
                    },
                    {
                        "technical_key": "turnover_estimated_in_formula",
                        "name": "Turnover stimato nella formula finale",
                        "description": "Correzione numerica da rischio rotazioni.",
                        "weight": None,
                        "weight_label": None,
                        "status": "non_applicata",
                        "impact": "Nessun impatto su expected_sot baseline.",
                        "interpretation": "Stima non ancora incorporata matematicamente.",
                    },
                ],
            },
        ],
    )


@router.get("/match-analysis-framework", response_model=MatchAnalysisFrameworkResponse)
def get_match_analysis_framework() -> MatchAnalysisFrameworkResponse:
    """
    Endpoint read-only e statico.

    Obiettivo: esporre una struttura consultabile delle variabili che il modello può valutare
    pre-partita per diversi mercati betting, senza modificare formule o prediction esistenti.
    """
    # Nota: per questo step NON usiamo DB e NON salviamo configurazioni.
    def wlabel(w: int) -> str:
        if w >= 90:
            return "Molto alta"
        if w >= 70:
            return "Alta"
        if w >= 40:
            return "Media"
        if w >= 10:
            return "Bassa"
        return "Non applicata"

    def v(
        *,
        area: str,
        key: str,
        name: str,
        description: str,
        markets: list[str],
        weight: int,
        data_source: str,
        status: str,
        applied_now: bool,
        notes: str | None = None,
    ) -> dict:
        return {
            "area": area,
            "key": key,
            "name": name,
            "description": description,
            "impacted_markets": markets,
            "theoretical_weight": int(weight),
            "weight_label": wlabel(int(weight)),
            "data_source": data_source,
            "implementation_status": status,
            "applied_now": bool(applied_now),
            "notes": notes,
        }

    all_markets = ["tiri_in_porta", "tiri_totali", "corner", "cartellini", "falli", "goal_over_under"]

    return MatchAnalysisFrameworkResponse(
        title="Match Analysis Framework",
        description=(
            "Struttura consultabile delle variabili che il modello può considerare per analizzare una partita "
            "prima di generare una previsione betting. Versione documentale/static."
        ),
        version="framework_v0_1",
        areas=[
            {
                "id": "base_match_data",
                "title": "Dati base partita",
                "description": "Variabili strutturali per collegare e contestualizzare tutte le analisi successive.",
                "variables": [
                    v(
                        area="Dati base partita",
                        key="squadra_casa",
                        name="Squadra casa",
                        description="Identità squadra casa.",
                        markets=all_markets,
                        weight=100,
                        data_source="Fixture API/DB",
                        status="implementata",
                        applied_now=True,
                        notes="Chiave per join e aggregazioni.",
                    ),
                    v(
                        area="Dati base partita",
                        key="squadra_trasferta",
                        name="Squadra trasferta",
                        description="Identità squadra ospite.",
                        markets=all_markets,
                        weight=100,
                        data_source="Fixture API/DB",
                        status="implementata",
                        applied_now=True,
                        notes="Chiave per join e aggregazioni.",
                    ),
                    v(
                        area="Dati base partita",
                        key="data_orario",
                        name="Data e orario",
                        description="Kickoff datetime.",
                        markets=all_markets,
                        weight=80,
                        data_source="Fixture API/DB",
                        status="implementata",
                        applied_now=True,
                        notes="Base per freshness e per distinguere pre-lineup vs official.",
                    ),
                    v(
                        area="Dati base partita",
                        key="round",
                        name="Giornata / round",
                        description="Giornata/turno del campionato.",
                        markets=all_markets,
                        weight=70,
                        data_source="Fixture API/DB",
                        status="implementata",
                        applied_now=True,
                        notes="Utile per logiche di fine stagione e risk flags.",
                    ),
                    v(
                        area="Dati base partita",
                        key="stadio",
                        name="Stadio",
                        description="Stadio della partita (se disponibile).",
                        markets=all_markets,
                        weight=20,
                        data_source="Fixture API",
                        status="da implementare",
                        applied_now=False,
                        notes="Non sempre disponibile o stabile.",
                    ),
                    v(
                        area="Dati base partita",
                        key="competizione",
                        name="Competizione",
                        description="Lega/competizione della partita.",
                        markets=all_markets,
                        weight=40,
                        data_source="League/Season API/DB",
                        status="implementata",
                        applied_now=True,
                        notes="Serve per medie di campionato e normalizzazioni.",
                    ),
                    v(
                        area="Dati base partita",
                        key="stato_partita",
                        name="Stato partita",
                        description="Stato (scheduled/live/finished).",
                        markets=all_markets,
                        weight=60,
                        data_source="Fixture API/DB",
                        status="implementata",
                        applied_now=True,
                        notes="Usata per filtri e validazioni.",
                    ),
                    v(
                        area="Dati base partita",
                        key="classifica_attuale",
                        name="Classifica attuale delle squadre",
                        description="Posizione/punti correnti e contesto classifica.",
                        markets=all_markets,
                        weight=60,
                        data_source="Standings API/DB",
                        status="parzialmente implementata",
                        applied_now=False,
                        notes="Dipende dalla disponibilità standings; utile per motivazione.",
                    ),
                    v(
                        area="Dati base partita",
                        key="fase_stagione",
                        name="Fase della stagione",
                        description="Inizio/metà/fine stagione.",
                        markets=all_markets,
                        weight=60,
                        data_source="Round + regole contesto",
                        status="solo debug",
                        applied_now=False,
                        notes="Usata come warning/risk, non come correzione numerica in questo step.",
                    ),
                    v(
                        area="Dati base partita",
                        key="tempo_al_kickoff",
                        name="Distanza temporale dal calcio d’inizio",
                        description="Tempo residuo al kickoff (ore/giorni).",
                        markets=all_markets,
                        weight=30,
                        data_source="Now() + kickoff",
                        status="implementata",
                        applied_now=True,
                        notes="Serve per distinguere pre-lineup vs official-lineup prediction.",
                    ),
                ],
            },
            {
                "id": "offensive_production",
                "title": "Produzione offensiva squadra",
                "description": "Volume e qualità della produzione offensiva pre-partita.",
                "variables": [
                    v(
                        area="Produzione offensiva squadra",
                        key="avg_sot_for",
                        name="Media tiri in porta fatti",
                        description="Media pre-match dei tiri in porta fatti dalla squadra.",
                        markets=["tiri_in_porta", "goal_over_under"],
                        weight=95,
                        data_source="Team stats / DB features",
                        status="implementata",
                        applied_now=True,
                        notes="Core baseline SOT.",
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="avg_shots_for",
                        name="Media tiri totali fatti",
                        description="Media pre-match dei tiri totali fatti dalla squadra.",
                        markets=["tiri_totali", "goal_over_under"],
                        weight=85,
                        data_source="Team stats",
                        status="implementata",
                        applied_now=False,
                        notes="Auditabile via Match Variable Audit (pre-match, no leakage).",
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="avg_box_shots_for",
                        name="Media tiri dentro area",
                        description="Media pre-match dei tiri dentro area.",
                        markets=["tiri_totali", "goal_over_under"],
                        weight=70,
                        data_source="Team stats (se disponibile)",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="avg_outbox_shots_for",
                        name="Media tiri fuori area",
                        description="Media pre-match dei tiri fuori area.",
                        markets=["tiri_totali"],
                        weight=55,
                        data_source="Team stats (se disponibile)",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="avg_goals_for",
                        name="Media goal fatti",
                        description="Media pre-match dei goal segnati.",
                        markets=["goal_over_under"],
                        weight=80,
                        data_source="Team stats",
                        status="da implementare",
                        applied_now=False,
                        notes="Da considerare separatamente dalle conversioni.",
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="conv_shots_to_sot",
                        name="Conversione tiri totali → tiri in porta",
                        description="Rapporto tra tiri totali e tiri in porta.",
                        markets=["tiri_totali", "tiri_in_porta"],
                        weight=65,
                        data_source="Derived (richiede tiri totali)",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="conv_sot_to_goals",
                        name="Conversione tiri in porta → goal",
                        description="Rapporto SOT→goal.",
                        markets=["goal_over_under"],
                        weight=65,
                        data_source="Derived",
                        status="da implementare",
                        applied_now=False,
                        notes="Attenzione a sample/varianza.",
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="xg_for",
                        name="xG",
                        description="Expected goals prodotti (se disponibile).",
                        markets=["goal_over_under", "tiri_in_porta", "tiri_totali"],
                        weight=70,
                        data_source="Advanced stats provider",
                        status="da implementare",
                        applied_now=False,
                        notes="Non sempre disponibile.",
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="big_chances_created",
                        name="Big chances create",
                        description="Numero di grandi occasioni create (se disponibile).",
                        markets=["goal_over_under"],
                        weight=60,
                        data_source="Advanced stats provider",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="avg_possession",
                        name="Possesso medio",
                        description="Possesso medio squadra.",
                        markets=["tiri_totali", "corner"],
                        weight=45,
                        data_source="Team stats",
                        status="da implementare",
                        applied_now=False,
                        notes="Impatto indiretto.",
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="key_passes",
                        name="Passaggi chiave",
                        description="Key passes (team o aggregazione player).",
                        markets=["tiri_totali", "goal_over_under"],
                        weight=55,
                        data_source="Player/team stats",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="crosses_for",
                        name="Cross effettuati",
                        description="Volume cross (indicatore pressione laterale).",
                        markets=["corner", "tiri_totali"],
                        weight=55,
                        data_source="Team/player stats",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="touches_box_for",
                        name="Tocchi in area avversaria",
                        description="Touches in opponent box (se disponibile).",
                        markets=["goal_over_under", "tiri_totali"],
                        weight=55,
                        data_source="Advanced stats provider",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="corners_for",
                        name="Corner offensivi prodotti",
                        description="Media corner prodotti.",
                        markets=["corner"],
                        weight=80,
                        data_source="Team stats",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="offensive_trend",
                        name="Trend offensivo crescente/decrescente",
                        description="Indicatore di trend offensivo recente.",
                        markets=all_markets,
                        weight=60,
                        data_source="Rolling windows (derived)",
                        status="parzialmente implementata",
                        applied_now=False,
                        notes="In parte coperto da last5; formalizzazione futura.",
                    ),
                    v(
                        area="Produzione offensiva squadra",
                        key="vs_strong_weak_offense",
                        name="Produzione offensiva contro squadre forti/deboli",
                        description="Split performance per tier avversario.",
                        markets=all_markets,
                        weight=45,
                        data_source="Standings tiers (derived)",
                        status="da implementare",
                        applied_now=False,
                        notes="Richiede definizione tiers.",
                    ),
                ],
            },
            {
                "id": "opponent_defense",
                "title": "Resistenza difensiva avversaria",
                "description": "Quanto l’avversario concede e con che trend.",
                "variables": [
                    v(
                        area="Resistenza difensiva avversaria",
                        key="avg_sot_conceded",
                        name="Tiri in porta concessi",
                        description="Media pre-match dei tiri in porta concessi dall’avversario.",
                        markets=["tiri_in_porta", "goal_over_under"],
                        weight=95,
                        data_source="Team stats / DB features",
                        status="implementata",
                        applied_now=True,
                        notes="Core baseline SOT (lato avversario).",
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="avg_shots_conceded",
                        name="Tiri totali concessi",
                        description="Media tiri totali concessi dall’avversario.",
                        markets=["tiri_totali", "goal_over_under"],
                        weight=85,
                        data_source="Team stats",
                        status="implementata",
                        applied_now=False,
                        notes="Auditabile via Match Variable Audit (concessi da riga avversaria).",
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="avg_box_shots_conceded",
                        name="Tiri dentro area concessi",
                        description="Media tiri dentro area concessi.",
                        markets=["tiri_totali", "goal_over_under"],
                        weight=70,
                        data_source="Team stats (se disponibile)",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="avg_outbox_shots_conceded",
                        name="Tiri fuori area concessi",
                        description="Media tiri fuori area concessi.",
                        markets=["tiri_totali"],
                        weight=55,
                        data_source="Team stats (se disponibile)",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="goals_conceded",
                        name="Goal concessi",
                        description="Media goal concessi.",
                        markets=["goal_over_under"],
                        weight=80,
                        data_source="Team stats",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="xga",
                        name="xGA",
                        description="Expected goals concessi (se disponibile).",
                        markets=["goal_over_under"],
                        weight=70,
                        data_source="Advanced stats provider",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="big_chances_conceded",
                        name="Big chances concesse",
                        description="Numero grandi occasioni concesse (se disponibile).",
                        markets=["goal_over_under"],
                        weight=60,
                        data_source="Advanced stats provider",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="corners_conceded",
                        name="Corner concessi",
                        description="Media corner concessi.",
                        markets=["corner"],
                        weight=75,
                        data_source="Team stats",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="crosses_conceded",
                        name="Cross concessi",
                        description="Volume cross concessi.",
                        markets=["corner"],
                        weight=50,
                        data_source="Team stats",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="recent_clean_sheets",
                        name="Clean sheet recenti",
                        description="Indicatore di clean sheet recenti.",
                        markets=["goal_over_under"],
                        weight=40,
                        data_source="Derived",
                        status="da implementare",
                        applied_now=False,
                        notes="Segnale spesso rumoroso.",
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="pressure_faced",
                        name="Pressione subita",
                        description="Pressione subita / under-pressure metric (se disponibile).",
                        markets=["tiri_totali", "corner"],
                        weight=40,
                        data_source="Advanced stats provider",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="defensive_errors",
                        name="Errori difensivi",
                        description="Errori che portano a tiri/goal (se disponibile).",
                        markets=["goal_over_under"],
                        weight=45,
                        data_source="Events/advanced stats",
                        status="da implementare",
                        applied_now=False,
                        notes="Definizione non standard.",
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="tiri_concessi_vs_simili",
                        name="Tiri concessi contro squadre simili",
                        description="Split concessioni vs squadre simili.",
                        markets=all_markets,
                        weight=45,
                        data_source="Clustering/tiers (derived)",
                        status="da implementare",
                        applied_now=False,
                        notes=None,
                    ),
                    v(
                        area="Resistenza difensiva avversaria",
                        key="defensive_trend",
                        name="Trend difensivo recente",
                        description="Indicatore trend difensivo recente.",
                        markets=all_markets,
                        weight=60,
                        data_source="Rolling windows (derived)",
                        status="parzialmente implementata",
                        applied_now=False,
                        notes="In parte coperto da last5 conceded.",
                    ),
                ],
            },
            {
                "id": "home_away",
                "title": "Rendimento casa / trasferta",
                "description": "Split contestuale casa/fuori su produzione e concessioni.",
                "variables": [
                    v(area="Rendimento casa / trasferta", key="home_avg_sot_for", name="Tiri in porta fatti in casa", description="SOT fatti quando la squadra gioca in casa.", markets=["tiri_in_porta"], weight=85, data_source="DB features (home split)", status="implementata", applied_now=True),
                    v(area="Rendimento casa / trasferta", key="away_avg_sot_for", name="Tiri in porta fatti in trasferta", description="SOT fatti quando la squadra gioca in trasferta.", markets=["tiri_in_porta"], weight=85, data_source="DB features (away split)", status="implementata", applied_now=True),
                    v(area="Rendimento casa / trasferta", key="home_avg_shots_for", name="Tiri totali fatti in casa", description="Tiri totali fatti in casa.", markets=["tiri_totali"], weight=70, data_source="Team stats home split", status="da implementare", applied_now=False),
                    v(area="Rendimento casa / trasferta", key="away_avg_shots_for", name="Tiri totali fatti in trasferta", description="Tiri totali fatti in trasferta.", markets=["tiri_totali"], weight=70, data_source="Team stats away split", status="da implementare", applied_now=False),
                    v(area="Rendimento casa / trasferta", key="home_avg_sot_conceded", name="Tiri concessi in casa", description="SOT concessi quando la squadra gioca in casa.", markets=["tiri_in_porta"], weight=75, data_source="DB features (home split)", status="implementata", applied_now=True),
                    v(area="Rendimento casa / trasferta", key="away_avg_sot_conceded", name="Tiri concessi in trasferta", description="SOT concessi quando la squadra gioca in trasferta.", markets=["tiri_in_porta"], weight=75, data_source="DB features (away split)", status="implementata", applied_now=True),
                    v(area="Rendimento casa / trasferta", key="home_avg_goals_for", name="Goal fatti casa", description="Media goal fatti in casa.", markets=["goal_over_under"], weight=65, data_source="Team stats home split", status="da implementare", applied_now=False),
                    v(area="Rendimento casa / trasferta", key="away_avg_goals_for", name="Goal fatti fuori", description="Media goal fatti in trasferta.", markets=["goal_over_under"], weight=65, data_source="Team stats away split", status="da implementare", applied_now=False),
                    v(area="Rendimento casa / trasferta", key="home_avg_goals_conceded", name="Goal subiti casa", description="Media goal subiti in casa.", markets=["goal_over_under"], weight=65, data_source="Team stats home split", status="da implementare", applied_now=False),
                    v(area="Rendimento casa / trasferta", key="away_avg_goals_conceded", name="Goal subiti fuori", description="Media goal subiti in trasferta.", markets=["goal_over_under"], weight=65, data_source="Team stats away split", status="da implementare", applied_now=False),
                    v(area="Rendimento casa / trasferta", key="home_corners_for", name="Corner prodotti casa", description="Media corner prodotti in casa.", markets=["corner"], weight=65, data_source="Team stats home split", status="da implementare", applied_now=False),
                    v(area="Rendimento casa / trasferta", key="away_corners_for", name="Corner prodotti fuori", description="Media corner prodotti in trasferta.", markets=["corner"], weight=65, data_source="Team stats away split", status="da implementare", applied_now=False),
                    v(area="Rendimento casa / trasferta", key="home_corners_conceded", name="Corner concessi casa", description="Media corner concessi in casa.", markets=["corner"], weight=65, data_source="Team stats home split", status="da implementare", applied_now=False),
                    v(area="Rendimento casa / trasferta", key="away_corners_conceded", name="Corner concessi fuori", description="Media corner concessi in trasferta.", markets=["corner"], weight=65, data_source="Team stats away split", status="da implementare", applied_now=False),
                    v(area="Rendimento casa / trasferta", key="home_cards", name="Cartellini casa/fuori", description="Media cartellini nel contesto casa/fuori.", markets=["cartellini"], weight=50, data_source="Ref/team stats", status="da implementare", applied_now=False),
                    v(area="Rendimento casa / trasferta", key="intensity_home_away", name="Intensità casa/fuori", description="Indicatore intensità casa vs trasferta.", markets=["falli","cartellini"], weight=45, data_source="Derived", status="da implementare", applied_now=False, notes="Definizione da standardizzare."),
                    v(area="Rendimento casa / trasferta", key="home_away_delta", name="Differenza rendimento casa/fuori", description="Differenza complessiva tra casa e trasferta.", markets=all_markets, weight=60, data_source="Derived", status="parzialmente implementata", applied_now=False),
                ],
            },
            {
                "id": "recent_form",
                "title": "Forma recente",
                "description": "Rolling windows e trend; importante capire contro chi è stata fatta.",
                "variables": [
                    v(area="Forma recente", key="last5_overall", name="Ultime 5 partite", description="Set/contesto ultime 5 partite.", markets=all_markets, weight=70, data_source="Fixture history", status="implementata", applied_now=True),
                    v(area="Forma recente", key="last10_overall", name="Ultime 10 partite", description="Set/contesto ultime 10 partite.", markets=all_markets, weight=55, data_source="Fixture history", status="da implementare", applied_now=False),
                    v(area="Forma recente", key="last5_home_for_home_team", name="Ultime 5 in casa (team casa)", description="Ultime 5 in casa per la squadra di casa.", markets=all_markets, weight=55, data_source="Fixture history", status="da implementare", applied_now=False),
                    v(area="Forma recente", key="last5_away_for_away_team", name="Ultime 5 in trasferta (team ospite)", description="Ultime 5 in trasferta per la squadra ospite.", markets=all_markets, weight=55, data_source="Fixture history", status="da implementare", applied_now=False),
                    v(area="Forma recente", key="last5_sot_for", name="Tiri in porta ultime 5", description="Media SOT fatti nelle ultime 5 partite.", markets=["tiri_in_porta"], weight=80, data_source="DB features (rolling last5)", status="implementata", applied_now=True),
                    v(area="Forma recente", key="last5_shots_for", name="Tiri totali ultime 5", description="Media tiri totali ultime 5.", markets=["tiri_totali"], weight=75, data_source="Team stats rolling", status="implementata", applied_now=False, notes="Auditabile via Match Variable Audit (rolling last5)."),
                    v(area="Forma recente", key="last5_sot_conceded", name="Tiri concessi ultime 5", description="Media SOT concessi nelle ultime 5.", markets=["tiri_in_porta"], weight=75, data_source="DB features (rolling last5)", status="implementata", applied_now=True),
                    v(area="Forma recente", key="last5_goals_for", name="Goal fatti ultime 5", description="Media goal fatti ultime 5.", markets=["goal_over_under"], weight=70, data_source="Derived rolling", status="da implementare", applied_now=False),
                    v(area="Forma recente", key="last5_goals_conceded", name="Goal subiti ultime 5", description="Media goal subiti ultime 5.", markets=["goal_over_under"], weight=70, data_source="Derived rolling", status="da implementare", applied_now=False),
                    v(area="Forma recente", key="last5_corners", name="Corner ultime 5", description="Media corner ultime 5.", markets=["corner"], weight=65, data_source="Derived rolling", status="da implementare", applied_now=False),
                    v(area="Forma recente", key="last5_cards", name="Cartellini ultime 5", description="Media cartellini ultime 5.", markets=["cartellini"], weight=55, data_source="Derived rolling", status="da implementare", applied_now=False),
                    v(area="Forma recente", key="momentum_trend", name="Trend positivo/negativo", description="Indicatore di momentum (trend).", markets=all_markets, weight=60, data_source="Derived", status="parzialmente implementata", applied_now=False),
                    v(area="Forma recente", key="form_vs_similar", name="Forma contro squadre simili", description="Performance recente vs avversari simili.", markets=all_markets, weight=45, data_source="Tiers/clustering", status="da implementare", applied_now=False),
                    v(area="Forma recente", key="strength_of_schedule", name="Strength of schedule recente", description="Difficoltà avversari recenti.", markets=all_markets, weight=55, data_source="Standings tiers", status="da implementare", applied_now=False),
                ],
            },
            {
                "id": "player_impact",
                "title": "Player impact",
                "description": "Forza offensiva della rosa e dei top shooters (non equivale alla formazione ufficiale).",
                "variables": [
                    v(area="Player impact", key="top_shooters_sot_per90", name="Top player per tiri in porta/90", description="Top shooter per SOT/90.", markets=["tiri_in_porta","goal_over_under"], weight=80, data_source="DB player profiles", status="implementata", applied_now=True, notes="Applicata nel live SOT v0.2 player adjusted."),
                    v(area="Player impact", key="top_shooters_shots_per90", name="Top player per tiri totali/90", description="Top shooter per tiri/90.", markets=["tiri_totali","goal_over_under"], weight=70, data_source="Player stats", status="da implementare", applied_now=False),
                    v(area="Player impact", key="player_team_sot_share", name="Quota tiri in porta della squadra per giocatore", description="Share SOT team per player.", markets=["tiri_in_porta"], weight=70, data_source="DB player profiles", status="implementata", applied_now=True),
                    v(area="Player impact", key="player_team_shots_share", name="Quota tiri totali della squadra per giocatore", description="Share shots team per player.", markets=["tiri_totali"], weight=60, data_source="Player stats", status="da implementare", applied_now=False),
                    v(area="Player impact", key="top_scorer", name="Capocannoniere squadra", description="Top scorer e peso nel team.", markets=["goal_over_under"], weight=50, data_source="Player stats", status="da implementare", applied_now=False),
                    v(area="Player impact", key="penalty_taker", name="Rigorista", description="Identità rigorista (se affidabile).", markets=["goal_over_under"], weight=45, data_source="Lineups/news", status="da implementare", applied_now=False, notes="Rumoroso senza fonte affidabile."),
                    v(area="Player impact", key="main_creator", name="Assistman / creatore principale", description="Creatore principale (key passes/assists).", markets=["goal_over_under","corner"], weight=45, data_source="Player stats", status="da implementare", applied_now=False),
                    v(area="Player impact", key="key_passes_per90", name="Passaggi chiave per 90", description="Key passes/90.", markets=["tiri_totali","goal_over_under"], weight=45, data_source="Player stats", status="da implementare", applied_now=False),
                    v(area="Player impact", key="crosses_per90", name="Cross per 90", description="Cross/90.", markets=["corner"], weight=45, data_source="Player stats", status="da implementare", applied_now=False),
                    v(area="Player impact", key="minutes_played", name="Minuti giocati", description="Minuti giocati nel campione.", markets=all_markets, weight=40, data_source="Player stats", status="implementata", applied_now=True),
                    v(area="Player impact", key="starts", name="Presenze da titolare", description="Starts nel campione.", markets=all_markets, weight=35, data_source="Player stats", status="implementata", applied_now=True),
                    v(area="Player impact", key="player_form", name="Stato di forma giocatore", description="Trend recente del player.", markets=all_markets, weight=40, data_source="Rolling player stats", status="da implementare", applied_now=False),
                    v(area="Player impact", key="sample_reliability", name="Affidabilità del campione dati", description="Robustezza profilo (minuti/presenze).", markets=all_markets, weight=60, data_source="Derived", status="implementata", applied_now=True),
                    v(area="Player impact", key="offensive_dependency", name="Dipendenza offensiva", description="Dipendenza da uno o pochi giocatori.", markets=all_markets, weight=60, data_source="Derived team shares", status="da implementare", applied_now=False),
                    v(area="Player impact", key="bench_depth", name="Panchina offensiva", description="Profondità panchina offensiva.", markets=all_markets, weight=35, data_source="Roster/player stats", status="da implementare", applied_now=False),
                    v(area="Player impact", key="important_returns", name="Rientri importanti", description="Rientri top player.", markets=all_markets, weight=40, data_source="Availability/news", status="da implementare", applied_now=False),
                ],
            },
            {
                "id": "injuries_availability",
                "title": "Assenti / infortunati / squalificati",
                "description": "Disponibilità giocatori e impatto sul match; distinguere assenza assorbita vs improvvisa.",
                "variables": [
                    v(area="Assenti / infortunati / squalificati", key="infortunati", name="Infortunati", description="Lista infortunati.", markets=all_markets, weight=85, data_source="Injuries provider", status="solo debug", applied_now=False, notes="Solo warning in questa fase."),
                    v(area="Assenti / infortunati / squalificati", key="squalificati", name="Squalificati", description="Lista squalificati.", markets=all_markets, weight=85, data_source="Discipline provider", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="indisponibili", name="Indisponibili", description="Indisponibili generici.", markets=all_markets, weight=65, data_source="Provider", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="diffidati", name="Diffidati", description="Diffidati/ballottaggi (se utile).", markets=all_markets, weight=35, data_source="News/provider", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="assenza_top_scorer", name="Assenza top scorer", description="Assenza del top scorer.", markets=["goal_over_under"], weight=95, data_source="Lineups/news", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="assenza_top_shooter", name="Assenza top shooter", description="Assenza del top shooter.", markets=["tiri_in_porta","tiri_totali"], weight=95, data_source="Lineups/news", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="assenza_rigorista", name="Assenza rigorista", description="Assenza del rigorista.", markets=["goal_over_under"], weight=55, data_source="Lineups/news", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="assenza_creatore", name="Assenza creatore principale", description="Assenza del creatore principale.", markets=["goal_over_under","corner"], weight=55, data_source="Lineups/news", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="assenza_regista", name="Assenza regista", description="Assenza del playmaker.", markets=all_markets, weight=45, data_source="Lineups/news", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="assenza_difensore_chiave", name="Assenza difensore chiave", description="Assenza difensore chiave.", markets=["goal_over_under"], weight=60, data_source="Lineups/news", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="assenza_portiere_titolare", name="Assenza portiere titolare", description="Assenza portiere titolare.", markets=["goal_over_under"], weight=70, data_source="Lineups/news", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="assenza_esterno_crossatore", name="Assenza esterno/crossatore", description="Assenza esterno/crossatore.", markets=["corner"], weight=55, data_source="Lineups/news", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="durata_assenza", name="Durata assenza", description="Durata assenza.", markets=all_markets, weight=40, data_source="Injuries provider", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="assenza_nuova_vs_assorbita", name="Assenza nuova o già assorbita", description="Assenza improvvisa vs già nei dati recenti.", markets=all_markets, weight=65, data_source="Derived", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="peso_assente_nel_team", name="Peso dell’assente nella squadra", description="Centralità dell’assente.", markets=all_markets, weight=70, data_source="Impact scores", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="probabile_sostituto", name="Probabile sostituto", description="Probabile sostituto.", markets=all_markets, weight=35, data_source="Lineups/news", status="da implementare", applied_now=False),
                    v(area="Assenti / infortunati / squalificati", key="gap_titolare_vs_sostituto", name="Differenza titolare vs sostituto", description="Gap qualità.", markets=all_markets, weight=60, data_source="Roster ratings", status="da implementare", applied_now=False),
                ],
            },
            {
                "id": "lineups",
                "title": "Formazioni probabili e ufficiali",
                "description": "Due modalità: pre-lineup prediction e official-lineup prediction.",
                "variables": [
                    {
                        "area": "Formazioni probabili e ufficiali",
                        "key": "official_lineup",
                        "name": "Formazione ufficiale",
                        "description": "XI ufficiale confermato.",
                        "impacted_markets": ["tiri_in_porta", "tiri_totali", "corner", "cartellini", "falli", "goal_over_under"],
                        "theoretical_weight": 95,
                        "weight_label": "Molto alta",
                        "data_source": "Official lineups feed",
                        "implementation_status": "da implementare",
                        "applied_now": False,
                        "notes": "Quando disponibile ha impatto forte; non implementato in questo step.",
                    }
                ],
            },
            {
                "id": "h2h",
                "title": "Scontri diretti / H2H",
                "description": "Segnale di contesto con peso basso/medio; campioni piccoli sono rumorosi.",
                "variables": [
                    {
                        "area": "Scontri diretti / H2H",
                        "key": "h2h_last5",
                        "name": "Ultimi 5 scontri diretti",
                        "description": "Riepilogo H2H sugli ultimi incontri conclusi.",
                        "impacted_markets": ["tiri_in_porta", "tiri_totali", "corner", "cartellini", "falli", "goal_over_under"],
                        "theoretical_weight": 35,
                        "weight_label": "Bassa",
                        "data_source": "H2H API + DB stats dove disponibili",
                        "implementation_status": "solo debug",
                        "applied_now": False,
                        "notes": "Da usare come warning/lettura, non come core numerico.",
                    }
                ],
            },
            {
                "id": "schedule_fatigue",
                "title": "Calendario / fatica / coppe",
                "description": "Congestione calendario e potenziale turnover/fatica.",
                "variables": [
                    {
                        "area": "Calendario / fatica / coppe",
                        "key": "rest_days",
                        "name": "Giorni di riposo",
                        "description": "Giorni di riposo rispetto all’ultima partita.",
                        "impacted_markets": ["tiri_in_porta", "tiri_totali", "corner", "cartellini", "falli", "goal_over_under"],
                        "theoretical_weight": 55,
                        "weight_label": "Media",
                        "data_source": "Fixture history (derived)",
                        "implementation_status": "da implementare",
                        "applied_now": False,
                        "notes": "Utile soprattutto in periodi con coppe.",
                    }
                ],
            },
            {
                "id": "motivation_context",
                "title": "Motivazione / classifica / valore reale partita",
                "description": "Contesto competitivo e rischio: previsione buona ma partita pericolosa.",
                "variables": [
                    {
                        "area": "Motivazione / classifica / valore reale partita",
                        "key": "late_season",
                        "name": "Ultime giornate",
                        "description": "Flag/scala che segnala fine stagione e potenziale volatilità.",
                        "impacted_markets": ["tiri_in_porta", "tiri_totali", "corner", "cartellini", "falli", "goal_over_under"],
                        "theoretical_weight": 70,
                        "weight_label": "Alta",
                        "data_source": "Round + regole contesto",
                        "implementation_status": "solo debug",
                        "applied_now": False,
                        "notes": "Al momento è un warning di lettura.",
                    }
                ],
            },
            {
                "id": "odds_market",
                "title": "Quote bookmaker e movimento linea",
                "description": "Layer per value e decisione finale; non necessariamente per stima statistica pura.",
                "variables": [
                    {
                        "area": "Quote bookmaker e movimento linea",
                        "key": "current_odds",
                        "name": "Quota attuale",
                        "description": "Quota corrente del mercato considerato.",
                        "impacted_markets": ["tiri_in_porta", "tiri_totali", "corner", "cartellini", "falli", "goal_over_under"],
                        "theoretical_weight": 80,
                        "weight_label": "Alta",
                        "data_source": "Odds provider",
                        "implementation_status": "da implementare",
                        "applied_now": False,
                        "notes": "Previsto per fase successiva; non implementato qui.",
                    }
                ],
            },
            {
                "id": "referee",
                "title": "Arbitro",
                "description": "Molto rilevante per cartellini/falli; impatto indiretto su ritmo.",
                "variables": [
                    {
                        "area": "Arbitro",
                        "key": "ref_yellow_avg",
                        "name": "Cartellini gialli medi",
                        "description": "Media gialli per partita dell’arbitro.",
                        "impacted_markets": ["cartellini"],
                        "theoretical_weight": 90,
                        "weight_label": "Molto alta",
                        "data_source": "Referee stats provider",
                        "implementation_status": "da implementare",
                        "applied_now": False,
                        "notes": "Driver principale mercato cartellini.",
                    }
                ],
            },
            {
                "id": "tactics_matchup",
                "title": "Stile tattico / matchup",
                "description": "Stile squadre e compatibilità del matchup; complesso da automatizzare bene.",
                "variables": [
                    {
                        "area": "Stile tattico / matchup",
                        "key": "expected_pace",
                        "name": "Ritmo previsto",
                        "description": "Stima del ritmo partita.",
                        "impacted_markets": ["tiri_in_porta", "tiri_totali", "corner", "falli", "cartellini", "goal_over_under"],
                        "theoretical_weight": 55,
                        "weight_label": "Media",
                        "data_source": "Style metrics / derived",
                        "implementation_status": "da implementare",
                        "applied_now": False,
                        "notes": "Inizialmente può essere warning qualitativo.",
                    }
                ],
            },
            {
                "id": "set_pieces",
                "title": "Set pieces / palle inattive",
                "description": "Corner e situazioni da fermo: rilevanti per corner e parte dei goal.",
                "variables": [
                    {
                        "area": "Set pieces / palle inattive",
                        "key": "corners_for",
                        "name": "Corner offensivi prodotti",
                        "description": "Media corner prodotti.",
                        "impacted_markets": ["corner"],
                        "theoretical_weight": 80,
                        "weight_label": "Alta",
                        "data_source": "Team stats",
                        "implementation_status": "da implementare",
                        "applied_now": False,
                        "notes": "Mercato corner dedicato.",
                    }
                ],
            },
            {
                "id": "goalkeepers",
                "title": "Portieri",
                "description": "Impatto su goal/over-under; effetto indiretto sui SOT→goal.",
                "variables": [
                    {
                        "area": "Portieri",
                        "key": "starting_goalkeeper",
                        "name": "Portiere titolare",
                        "description": "Identità e qualità del portiere titolare.",
                        "impacted_markets": ["goal_over_under"],
                        "theoretical_weight": 60,
                        "weight_label": "Media",
                        "data_source": "Lineups/keeper stats",
                        "implementation_status": "da implementare",
                        "applied_now": False,
                        "notes": "Da integrare con ufficiali/pre-lineup.",
                    }
                ],
            },
            {
                "id": "coach_change",
                "title": "Cambio allenatore / stato tecnico",
                "description": "Cambio coach e shock di breve periodo su stile/volumi.",
                "variables": [
                    {
                        "area": "Cambio allenatore / stato tecnico",
                        "key": "coach_changed",
                        "name": "Allenatore cambiato",
                        "description": "Flag cambio allenatore recente.",
                        "impacted_markets": ["tiri_in_porta", "tiri_totali", "corner", "cartellini", "falli", "goal_over_under"],
                        "theoretical_weight": 70,
                        "weight_label": "Alta",
                        "data_source": "Team news/provider",
                        "implementation_status": "da implementare",
                        "applied_now": False,
                        "notes": "Da leggere con cautela; effetto non lineare.",
                    }
                ],
            },
            {
                "id": "sentiment_news",
                "title": "Sentiment / news / contesto esterno",
                "description": "Layer rumoroso: inizialmente warning qualitativo, non correzione automatica.",
                "variables": [
                    {
                        "area": "Sentiment / news / contesto esterno",
                        "key": "injury_news",
                        "name": "News infortuni",
                        "description": "Segnali da news su potenziali assenze.",
                        "impacted_markets": ["tiri_in_porta", "tiri_totali", "corner", "cartellini", "falli", "goal_over_under"],
                        "theoretical_weight": 35,
                        "weight_label": "Bassa",
                        "data_source": "News/NLP (futuro)",
                        "implementation_status": "da implementare",
                        "applied_now": False,
                        "notes": "Rumoroso; usare come warning finché non validato.",
                    }
                ],
            },
            {
                "id": "data_quality_confidence",
                "title": "Qualità dati e confidence",
                "description": "Completezza, fallback e qualità: influenza lettura e decisione finale.",
                "variables": [
                    {
                        "area": "Qualità dati e confidence",
                        "key": "fallbacks_used",
                        "name": "Fallback usati",
                        "description": "Indicatori che segnalano sostituzioni/approssimazioni nei fattori.",
                        "impacted_markets": ["tiri_in_porta", "tiri_totali", "corner", "cartellini", "falli", "goal_over_under"],
                        "theoretical_weight": 80,
                        "weight_label": "Alta",
                        "data_source": "Model breakdown flags",
                        "implementation_status": "implementata",
                        "applied_now": True,
                        "notes": "Aumenta prudenza; non è una feature “di stima”, ma di affidabilità.",
                    },
                    {
                        "area": "Qualità dati e confidence",
                        "key": "prediction_confidence",
                        "name": "Prediction confidence",
                        "description": "Punteggio euristico di lettura della previsione.",
                        "impacted_markets": ["tiri_in_porta"],
                        "theoretical_weight": 85,
                        "weight_label": "Alta",
                        "data_source": "Model output",
                        "implementation_status": "implementata",
                        "applied_now": True,
                        "notes": "Non è probabilità calibrata.",
                    },
                ],
            },
            {
                "id": "no_bet_risk_management",
                "title": "Regole no bet / risk management",
                "description": "Regole per evitare giocate quando rischio/qualità dati è troppo alta.",
                "variables": [
                    {
                        "area": "Regole no bet / risk management",
                        "key": "insufficient_data",
                        "name": "Dati insufficienti",
                        "description": "Condizione di stop quando non c’è storia affidabile.",
                        "impacted_markets": ["tiri_in_porta", "tiri_totali", "corner", "cartellini", "falli", "goal_over_under"],
                        "theoretical_weight": 95,
                        "weight_label": "Molto alta",
                        "data_source": "Quality layer",
                        "implementation_status": "da implementare",
                        "applied_now": False,
                        "notes": "Da introdurre come policy di betting, non come formula.",
                    }
                ],
            },
        ],
        market_frameworks=[
            {
                "id": "tiri_in_porta",
                "title": "Framework tiri in porta",
                "primary_variables": [
                    "avg_sot_for",
                    "avg_sot_conceded",
                    "home_away_sot_for",
                    "home_away_sot_conceded",
                    "last5_sot_for",
                    "last5_sot_conceded",
                    "top_shooters_sot_per90",
                ],
                "secondary_variables": ["fallbacks_used", "tempo_al_kickoff", "expected_pace"],
                "warning_variables": ["late_season", "turnover_risk", "low_or_uncertain_motivation"],
                "less_relevant_variables": ["stadio", "ref_added_time"],
            },
            {
                "id": "tiri_totali",
                "title": "Framework tiri totali",
                "primary_variables": ["avg_shots_for", "avg_shots_conceded", "avg_possession", "expected_game_state", "last5_shots_for"],
                "secondary_variables": ["long_shot_team", "high_press", "shots_when_ahead", "shots_when_behind"],
                "warning_variables": ["congested_schedule", "rotations", "lineups_too_uncertain"],
                "less_relevant_variables": ["ref_red_avg"],
            },
            {
                "id": "corner",
                "title": "Framework corner",
                "primary_variables": ["corners_for", "corners_conceded", "crosses_for", "crossing_team", "wide_attack", "expected_pace"],
                "secondary_variables": ["set_piece_corners_for", "set_piece_corners_against", "wide_players"],
                "warning_variables": ["official_lineup", "injury_news"],
                "less_relevant_variables": ["h2h_wdl"],
            },
            {
                "id": "cartellini",
                "title": "Framework cartellini",
                "primary_variables": ["ref_yellow_avg", "ref_fouls_avg", "derby_rivalry", "relegation_race", "high_press"],
                "secondary_variables": ["h2h_last5", "environment_pressure", "expected_pace"],
                "warning_variables": ["sentiment_news"],
                "less_relevant_variables": ["avg_possession"],
            },
            {
                "id": "falli",
                "title": "Framework falli",
                "primary_variables": ["ref_fouls_avg", "high_press", "key_duels", "expected_pace"],
                "secondary_variables": ["environment_pressure", "derby_rivalry"],
                "warning_variables": ["lineups_too_uncertain"],
                "less_relevant_variables": ["set_piece_goals"],
            },
            {
                "id": "goal_over_under",
                "title": "Framework goal / over-under",
                "primary_variables": ["avg_goals_for", "goals_conceded", "conv_sot_to_goals", "xg_for", "xga", "starting_goalkeeper"],
                "secondary_variables": ["top_scorer", "missing_goalkeeper", "expected_game_state"],
                "warning_variables": ["late_season_danger", "unquantified_negative_news"],
                "less_relevant_variables": ["h2h_wdl"],
            },
        ],
        future_editable_weights={
            "enabled_now": False,
            "planned": True,
            "description": "In futuro i pesi potranno essere modificati da frontend e salvati come configurazione modello.",
        },
    )
